### ISSUE TITLE
Implement support for use of numpy array notation when backwards converting nxdl to yaml

### ISSUE THREAD

**Issue by mkuehbach** [FAIRmat-NFDI/pynxtools#151]
For most dimensions groups in NXDL files only the "rank" and "dim" group with "index" "value" XML tags are used.
In this case numpy shorthand notation can be used. This is currently implemented when converting forward
i.e. yaml to nxdl but not when converting backwards. The backwards conversion is should fall back to the
current "dimensions:" notation when dimensions have docs or constraints at the "dim" level like seen in NXstxm or NXmx
Otherwise the numpy notation can be used

**Comment by mkuehbach** [comment]
Possible logic to add in xml_handle_dimension could be:
If dimensions group has only the attribute "rank" with its value purely integer and
all child "dim" groups have only tags "index" and "value" then use the numpy notation otherwise
proceed as usual "dimensions" group notation.

**Comment by sherjeelshabih** [comment]
@mkuehbach has this been addressed already? If not, we can close this here and move it to the nyaml2nxdl repo.

**Comment by mkuehbach** [comment]
@sherjeelshabih not that I know of @RubelMozumder ?

**Comment by RubelMozumder** [comment]
> @sherjeelshabih not that I know of @RubelMozumder ?

I have not made the forward conversion, I am a bit confused. 
At this moment dimension works as follows:
```yaml
# 2D particle motion
dimensions:
   rank: 2
   dim: [[0, x coordinate], [1, y coordinate]]
   dim_parameters:
      doc: ["Position of particle on x-axis.","Position of particle on y-axis."]
```
