### ISSUE TITLE
[Docs]: customize copy code button

### ISSUE THREAD

**Issue by lukaspie** [FAIRmat-NFDI/pynxtools#406]
If we have something like 
```console
user@box:~$ dataconverter generate-template --nxdl NXmynxdl
```
in the docs, the "copy code" option will also copy "user@box". We should customize the codebox so only `dataconverter generate-template --nxdl NXmynxdl` gets copied.

There seems to be some solution along the lines of changing the `extras.css` file:
```css
.codehilite .no-copy {
    user-select: none;       /* Prevents text selection */
    pointer-events: none;    /* Prevents interaction */
    color: #6a737d;          /* Optional: style the prefix to look like a prompt */
}
´``
and then using
```console
<span class="no-copy">user@box:~$</span> dataconverter generate-template --nxdl NXmynxdl
```

But this does not yet work out of the box.
